function applyJob(i){let j=jobsData[i];s.job={title:j[0],salary:j[1]};s.performance=55;add('💼','You started working as '+j[0]+'.');render()}
function startBiz(i){let b=bizDefs[i];s.cash-=b[1];s.businesses.push({name:b[0],cost:b[1],baseRev:b[2],baseExp:b[3],valuation:b[1],locations:1,employees:2,franchises:0,marketShare:1,public:false,lastProfit:0});render()}
function upgradeBiz(i){let b=s.businesses[i],c=Math.round(b.cost*.25);if(s.cash<c)return toast('Not enough cash');s.cash-=c;b.baseRev=Math.round(b.baseRev*1.2);b.valuation=Math.round(b.valuation*1.18);render()}
function hire(i){if(s.cash<5000)return toast('Need $5,000');s.cash-=5000;s.businesses[i].employees++;render()}
function expandBiz(i){let b=s.businesses[i],c=Math.round(b.cost*.7);if(s.cash<c)return toast('Not enough cash');s.cash-=c;b.locations++;b.employees+=2;b.baseRev=Math.round(b.baseRev*1.55);b.baseExp=Math.round(b.baseExp*1.35);b.valuation=Math.round(b.valuation*1.5);b.marketShare+=2;render()}
function franchise(i){let b=s.businesses[i],fee=Math.round(b.cost*.6);s.cash+=fee;b.franchises++;b.valuation+=fee*2;b.marketShare+=1.5;render()}
function buyRival(i){let b=s.businesses[i],c=Math.round(b.valuation*.35);if(s.cash<c)return toast('Need '+money(c));s.cash-=c;b.locations+=2;b.marketShare+=6;b.valuation=Math.round(b.valuation*1.45);render()}
function ipo(i){let b=s.businesses[i],raise=Math.round(b.valuation*.65);s.cash+=raise;b.public=true;b.valuation=Math.round(b.valuation*2.4);render()}
function trade(i,amt){let m=marketDefs[i],shares=amt>0?amt/m[1]:1,c=shares*m[1];if(amt>0){if(s.cash<c)return toast('Not enough cash');s.cash-=c;s.holdings[i]=(s.holdings[i]||0)+shares}else{if((s.holdings[i]||0)<1)return toast('No shares');s.holdings[i]-=1;s.cash+=m[1]}render()}
function buyProperty(i){let p=propertyDefs[i];s.cash-=p[2];s.properties.push({name:p[0],value:p[1],mortgage:p[1]-p[2],rent:p[3],expenses:p[4],lastRent:0});render()}
function sellProperty(i){let p=s.properties[i];s.cash+=Math.round(p.value*.94)-p.mortgage;s.properties.splice(i,1);render()}
function findDate(){let names=['Jordan Lee','Taylor Morgan','Casey Smith','Riley Brooks'];s.dating={name:names[Math.floor(Math.random()*names.length)],relationship:65};render()}
function dateNight(){let p=s.spouse||s.dating;p.relationship=clamp(p.relationship+8);s.happy=clamp(s.happy+5);render()}
function propose(){if(s.dating.relationship<70)return toast('Build the relationship first');s.spouse=s.dating;s.dating=null;render()}
function haveChild(){let names=['Avery','Noah','Mia','Liam','Emma'];s.children.push({name:names[Math.floor(Math.random()*names.length)],age:0,smart:Math.round(45+Math.random()*45),health:80,relationship:75});render()}
function spendChild(i){s.children[i].relationship=clamp(s.children[i].relationship+8);render()}
function buyVehicle(i){let v=vehicleDefs[i];s.cash-=v[1];s.vehicles.push({name:v[0],value:v[1],depr:v[2],cost:v[3],condition:100});render()}
function sellVehicle(i){s.cash+=Math.round(s.vehicles[i].value*.9);s.vehicles.splice(i,1);render()}
function fundraise(){let amount=Math.round(5000+s.politics.reputation*700+Math.random()*25000);s.politics.campaignFunds+=amount;s.politics.reputation=clamp(s.politics.reputation+2);add('💰','You raised '+money(amount)+' for your campaign.');render()}
function townHall(){s.politics.approval=clamp(s.politics.approval+6);s.politics.reputation=clamp(s.politics.reputation+3);s.cash=Math.max(0,s.cash-5000);render()}
function runElection(i){let o=offices[i],available=s.cash+s.politics.campaignFunds;if(available<o.cost)return toast('Not enough campaign money');let fromFunds=Math.min(s.politics.campaignFunds,o.cost);s.politics.campaignFunds-=fromFunds;s.cash-=o.cost-fromFunds;let chance=.35+s.politics.reputation/180+s.looks/500+s.smart/600;if(Math.random()<chance){s.politics.office=o.name;s.politics.termLeft=o.term;s.politics.approval=52;s.politics.terms++;s.politics.reputation=clamp(s.politics.reputation+12);s.job=null;add('🏛️','You won the election for '+o.name+'!')}else{add('🗳️','You lost the election for '+o.name+'.');s.politics.reputation=clamp(s.politics.reputation+3)}render()}
function passPolicy(i){let p=policyDefs[i];s.politics.approval=clamp(s.politics.approval+p[1]+Math.random()*8-4);s.politics.reputation=clamp(s.politics.reputation+p[3]);s.bizSkill=clamp(s.bizSkill+p[2]);s.politics.policies++;add('📜','You signed '+p[0]+'.');render()}
function resignOffice(){add('🏛️','You resigned as '+s.politics.office+'.');s.politics.office=null;s.politics.termLeft=0;render()}
function enlist(i,officer){let b=militaryBranches[i];if(s.job||s.politics.office)return toast('Leave your current position first');if(s.age<b.minAge||s.age>b.maxAge||s.health<b.minHealth||s.smart<b.minSmart)return toast('You do not meet the requirements');s.military={...s.military,active:true,branch:b.name,rankIndex:0,officer:!!officer,years:0,performance:officer?62:55,deployments:s.military.deployments||0,medals:s.military.medals||0,injuries:s.military.injuries||0,discharge:null,veteran:false,benefits:0};s.job=null;s.health=clamp(s.health+b.fitness);s.smart=clamp(s.smart+b.skill);add(b.icon,'You joined the '+b.name+(officer?' as an officer candidate.':'.'));render()}
function militaryTraining(){if(!s.military.active)return;s.military.performance=clamp(s.military.performance+10);s.health=clamp(s.health+5);s.happy=clamp(s.happy-2);add('🏋️','You completed intensive military training.');render()}
function volunteerDeployment(){if(!s.military.active)return;let b=militaryBranches.find(x=>x.name===s.military.branch);s.military.deployments++;s.military.performance=clamp(s.military.performance+8);let r=Math.random();if(r<b.risk*.35){s.military.injuries++;let damage=Math.round(8+Math.random()*20);s.health=clamp(s.health-damage);add('🩹','You were injured during deployment and lost '+damage+' health.')}else if(r<b.risk+.25){s.military.medals++;s.military.performance=clamp(s.military.performance+10);add('🎖️','You earned a medal for distinguished service.')}else{add('🌍','You completed a successful deployment.')}render()}
function requestPromotion(){if(!s.military.active)return;let list=s.military.officer?officerRanks:enlistedRanks;if(s.military.rankIndex>=list.length-1)return toast('You are already at the highest rank');let need=58+s.military.rankIndex*4;if(s.military.performance<need)return toast('Performance must reach '+need+'%');let chance=.45+s.military.performance/200+s.military.medals*.03;if(Math.random()<chance){s.military.rankIndex++;s.military.performance=clamp(s.military.performance-12);add('⬆️','You were promoted to '+militaryRank()+'.')}else{add('📋','Your promotion request was denied.')}render()}
function leaveMilitary(){if(!s.military.active)return;let years=s.military.years,good=s.military.performance>=40;let discharge=years>=4&&good?'Honorable':good?'General':'Other Than Honorable';s.military.active=false;s.military.veteran=discharge==='Honorable'||discharge==='General';s.military.discharge=discharge;s.military.benefits=discharge==='Honorable'?Math.round(6000+years*1800+s.military.rankIndex*900):discharge==='General'?Math.round(2500+years*700):0;s.politics.reputation=clamp(s.politics.reputation+(discharge==='Honorable'?12:discharge==='General'?4:-10));add('🎖️','You left the '+s.military.branch+' with a '+discharge+' discharge.');render()}
function useVeteranPath(){if(!s.military.veteran)return;let options=[['Federal Security Specialist',78000],['Emergency Management Officer',82000],['Defense Contractor',105000],['Government Operations Manager',92000]];let pick=options[Math.min(options.length-1,Math.floor((s.military.rankIndex+s.military.years/4)/3))];s.job={title:pick[0],salary:pick[1]+s.military.rankIndex*2500};s.performance=65;s.politics.reputation=clamp(s.politics.reputation+5);add('🏛️','Your veteran experience helped you become a '+pick[0]+'.');render()}
function runMilitaryYear(){if(!s.military.active){if(s.military.veteran&&s.military.benefits){s.cash+=s.military.benefits;s.lastPassive+=s.military.benefits}return}let b=militaryBranches.find(x=>x.name===s.military.branch),rankPay=1+s.military.rankIndex*(s.military.officer?.11:.07),pay=Math.round(b.basePay*rankPay);s.cash+=pay;s.military.years++;s.military.performance=clamp(s.military.performance+Math.random()*10-3);s.health=clamp(s.health+b.fitness*.3);if(Math.random()<b.risk){s.military.deployments++;let r=Math.random();if(r<.28){s.military.injuries++;s.health=clamp(s.health-(8+Math.random()*18));add('🩹','You were injured during a military deployment.')}else if(r<.58){s.military.medals++;s.military.performance=clamp(s.military.performance+9);add('🎖️','You earned a military decoration.')}else add('🌍','You returned from deployment safely.')}if(s.military.performance>84&&Math.random()<.42){let list=s.military.officer?officerRanks:enlistedRanks;if(s.military.rankIndex<list.length-1){s.military.rankIndex++;s.military.performance=68;add('⬆️','You were promoted to '+militaryRank()+'.')}}if(s.health<25){s.military.active=false;s.military.veteran=true;s.military.discharge='Medical';s.military.benefits=Math.round(9000+s.military.years*1400);add('🏥','You received a medical discharge from the '+s.military.branch+'.')}}
function runYear(){s.lastPassive=0;if(s.job){let d=s.workMode==='hard'?14:s.workMode==='slack'?-18:2;s.performance=clamp(s.performance+d+Math.random()*6-3);s.cash+=s.job.salary;if(s.performance>88)s.job.salary=Math.round(s.job.salary*1.1);if(s.performance<20&&Math.random()<.5)s.job=null;s.workMode='normal'}runMilitaryYear();s.businesses.forEach(b=>{let profit=Math.round((b.baseRev*(.8+s.bizSkill/160)*(1+b.locations*.12+b.franchises*.06)-b.baseExp-b.employees*5000)*(.82+Math.random()*.36));b.lastProfit=profit;s.cash+=profit;s.lastPassive+=profit;b.valuation=Math.max(b.cost,Math.round(b.valuation*(1.02+Math.random()*.15)+(profit>0?profit*.25:profit*.1)))});s.marketCycle=['Bull','Normal','Normal','Bear'][Math.floor(Math.random()*4)];marketDefs.forEach((m,i)=>{let factor=s.marketCycle==='Bull'?1.15:s.marketCycle==='Bear'?.82:1;m[1]=Math.max(.1,m[1]*(1+m[2]+(Math.random()-.5)*m[4])*factor);let div=(s.holdings[i]||0)*m[1]*m[3];s.cash+=div;s.lastPassive+=div});s.properties.forEach(p=>{let profit=Math.round(p.rent*12*(.75+Math.random()*.25)-p.expenses-p.mortgage*.05);p.lastRent=profit;s.cash+=profit;s.lastPassive+=profit;p.mortgage=Math.max(0,p.mortgage-Math.round(p.mortgage*.02));p.value=Math.round(p.value*(1.01+Math.random()*.06))});s.vehicles.forEach(v=>{s.cash-=v.cost;v.value=Math.round(v.value*v.depr);v.condition=clamp(v.condition-(5+Math.random()*10))});s.children.forEach(c=>{c.age++;c.relationship=clamp(c.relationship-Math.random()*4)});if(s.politics.office){let o=offices.find(x=>x.name===s.politics.office);s.cash+=o.salary;s.politics.termLeft--;s.politics.approval=clamp(s.politics.approval+Math.random()*12-6);if(Math.random()<.12){s.politics.scandals++;s.politics.approval=clamp(s.politics.approval-18);s.politics.reputation=clamp(s.politics.reputation-10);add('📰','A political scandal hurt your approval.')}if(s.politics.termLeft<=0){add('🏛️','Your term as '+s.politics.office+' ended.');s.politics.office=null}}s.savings=Math.round(s.savings*1.03);s.health=clamp(s.health-(s.age>55?2:0));s.happy=clamp(s.happy+Math.random()*6-3)}
function ageUp(){s.age++;runYear();add('✨','Another year passed.');render()}
function confirmResetLife(){if(!window.confirm('Restart your life? This removes your current character and all saved progress.'))return;['lifeGameP9','lifeGameP456','lifeGameP3','lifeGameP2','lifeGamePhase1','lifegame','lifegame2'].forEach(k=>localStorage.removeItem(k));location.reload()}
let tt;function toast(x){let t=document.getElementById('toast');t.textContent=x;t.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('on'),1700)}render();