function applyJob(i){let j=jobsData[i];s.job={title:j[0],salary:j[1]};s.performance=55;add('💼','You started working as '+j[0]+'.');render()}
function startBiz(i){let b=bizDefs[i];s.cash-=b[1];s.businesses.push({name:b[0],cost:b[1],baseRev:b[2],baseExp:b[3],valuation:b[1],locations:1,employees:2,franchises:0,marketShare:1,public:false,lastProfit:0});render()}
function upgradeBiz(i){let b=s.businesses[i],c=Math.round(b.cost*.25);if(s.cash<c)return toast('Not enough cash');s.cash-=c;b.baseRev=Math.round(b.baseRev*1.2);b.valuation=Math.round(b.valuation*1.18);render()}
function hire(i){if(s.cash<5000)return toast('Need $5,000');s.cash-=5000;s.businesses[i].employees++;render()}
function expandBiz(i){let b=s.businesses[i],c=Math.round(b.cost*.7);if(s.cash<c)return toast('Not enough cash');s.cash-=c;b.locations++;b.employees+=2;b.baseRev=Math.round(b.baseRev*1.55);b.baseExp=Math.round(b.baseExp*1.35);b.valuation=Math.round(b.valuation*1.5);b.marketShare+=2;render()}
function franchise(i){let b=s.businesses[i],fee=Math.round(b.cost*.6);s.cash+=fee;b.franchises++;b.valuation+=fee*2;b.marketShare+=1.5;render()}
function buyRival(i){let b=s.businesses[i],c=Math.round(b.valuation*.35);if(s.cash<c)return toast('Need '+money(c));s.cash-=c;b.locations+=2;b.marketShare+=6;b.valuation=Math.round(b.valuation*1.45);render()}
function ipo(i){let b=s.businesses[i],raise=Math.round(b.valuation*.65);s.cash+=raise;b.public=true;b.valuation=Math.round(b.valuation*2.4);render()}
function trade(i,amt){let m=marketDefs[i],shares=amt>0?amt/m[1]:1,c=shares*m[1];if(amt>0){if(s.cash<c)return toast('Not enough cash');s.cash-=c;s.holdings[i]=(s.holdings[i]||0)+shares}else{if((s.holdings[i]||0)<1)return toast('No shares');s.holdings[i]-=1;s.cash+=m[1]}render()}
function buyProperty(i){let p=propertyDefs[i];s.cash-=p[2];s.properties.push({name:p[0],value:p[1],mortgage:p[1]-p[2],rent:p[3],expenses:p[4],lastRent:0});render()}
function sellProperty(i){let p=s.properties[i];s.cash+=Math.round(p.value*.94)-p.mortgage;s.properties.splice(i,1);render()}
function findDate(){let names=['Jordan Lee','Taylor Morgan','Casey Smith','Riley Brooks'];s.dating={name:names[Math.floor(Math.random()*names.length)],relationship:65};render()}
function dateNight(){let p=s.spouse||s.dating;p.relationship=clamp(p.relationship+8);s.happy=clamp(s.happy+5);render()}
function propose(){if(s.dating.relationship<70)return toast('Build the relationship first');s.spouse=s.dating;s.dating=null;render()}
function haveChild(){let names=['Avery','Noah','Mia','Liam','Emma'];s.children.push({name:names[Math.floor(Math.random()*names.length)],age:0,smart:Math.round(45+Math.random()*45),health:80,relationship:75});render()}
function spendChild(i){s.children[i].relationship=clamp(s.children[i].relationship+8);render()}
function buyVehicle(i){let v=vehicleDefs[i];s.cash-=v[1];s.vehicles.push({name:v[0],value:v[1],depr:v[2],cost:v[3],condition:100});render()}
function sellVehicle(i){s.cash+=Math.round(s.vehicles[i].value*.9);s.vehicles.splice(i,1);render()}
function fundraise(){let amount=Math.round(5000+s.politics.reputation*700+Math.random()*25000);s.politics.campaignFunds+=amount;s.politics.reputation=clamp(s.politics.reputation+2);add('💰','You raised '+money(amount)+' for your campaign.');render()}
function townHall(){s.politics.approval=clamp(s.politics.approval+6);s.politics.reputation=clamp(s.politics.reputation+3);s.cash=Math.max(0,s.cash-5000);render()}
function runElection(i){let o=offices[i],available=s.cash+s.politics.campaignFunds;if(available<o.cost)return toast('Not enough campaign money');let fromFunds=Math.min(s.politics.campaignFunds,o.cost);s.politics.campaignFunds-=fromFunds;s.cash-=o.cost-fromFunds;let chance=.35+s.politics.reputation/180+s.looks/500+s.smart/600;if(Math.random()<chance){s.politics.office=o.name;s.politics.termLeft=o.term;s.politics.approval=52;s.politics.terms++;s.politics.reputation=clamp(s.politics.reputation+12);s.job=null;add('🏛️','You won the election for '+o.name+'!')}else{add('🗳️','You lost the election for '+o.name+'.');s.politics.reputation=clamp(s.politics.reputation+3)}render()}
function passPolicy(i){let p=policyDefs[i];s.politics.approval=clamp(s.politics.approval+p[1]+Math.random()*8-4);s.politics.reputation=clamp(s.politics.reputation+p[3]);s.bizSkill=clamp(s.bizSkill+p[2]);s.politics.policies++;add('📜','You signed '+p[0]+'.');render()}
function resignOffice(){add('🏛️','You resigned as '+s.politics.office+'.');s.politics.office=null;s.politics.termLeft=0;render()}
function runYear(){s.lastPassive=0;if(s.job){let d=s.workMode==='hard'?14:s.workMode==='slack'?-18:2;s.performance=clamp(s.performance+d+Math.random()*6-3);s.cash+=s.job.salary;if(s.performance>88)s.job.salary=Math.round(s.job.salary*1.1);if(s.performance<20&&Math.random()<.5)s.job=null;s.workMode='normal'}s.businesses.forEach(b=>{let profit=Math.round((b.baseRev*(.8+s.bizSkill/160)*(1+b.locations*.12+b.franchises*.06)-b.baseExp-b.employees*5000)*(.82+Math.random()*.36));b.lastProfit=profit;s.cash+=profit;s.lastPassive+=profit;b.valuation=Math.max(b.cost,Math.round(b.valuation*(1.02+Math.random()*.15)+(profit>0?profit*.25:profit*.1)))});s.marketCycle=['Bull','Normal','Normal','Bear'][Math.floor(Math.random()*4)];marketDefs.forEach((m,i)=>{let factor=s.marketCycle==='Bull'?1.15:s.marketCycle==='Bear'?.82:1;m[1]=Math.max(.1,m[1]*(1+m[2]+(Math.random()-.5)*m[4])*factor);let div=(s.holdings[i]||0)*m[1]*m[3];s.cash+=div;s.lastPassive+=div});s.properties.forEach(p=>{let profit=Math.round(p.rent*12*(.75+Math.random()*.25)-p.expenses-p.mortgage*.05);p.lastRent=profit;s.cash+=profit;s.lastPassive+=profit;p.mortgage=Math.max(0,p.mortgage-Math.round(p.mortgage*.02));p.value=Math.round(p.value*(1.01+Math.random()*.06))});s.vehicles.forEach(v=>{s.cash-=v.cost;v.value=Math.round(v.value*v.depr);v.condition=clamp(v.condition-(5+Math.random()*10))});s.children.forEach(c=>{c.age++;c.relationship=clamp(c.relationship-Math.random()*4)});if(s.politics.office){let o=offices.find(x=>x.name===s.politics.office);s.cash+=o.salary;s.politics.termLeft--;s.politics.approval=clamp(s.politics.approval+Math.random()*12-6);if(Math.random()<.12){s.politics.scandals++;s.politics.approval=clamp(s.politics.approval-18);s.politics.reputation=clamp(s.politics.reputation-10);add('📰','A political scandal hurt your approval.')}if(s.politics.termLeft<=0){add('🏛️','Your term as '+s.politics.office+' ended.');s.politics.office=null}}s.savings=Math.round(s.savings*1.03);s.health=clamp(s.health-(s.age>55?2:0));s.happy=clamp(s.happy+Math.random()*6-3)}
function ageUp(){s.age++;runYear();add('✨','Another year passed.');render()}
let tt;function toast(x){let t=document.getElementById('toast');t.textContent=x;t.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('on'),1700)}render();