const defaults={name:'Alex Johnson',age:18,generation:1,cash:250000,savings:0,health:85,happy:75,smart:78,looks:68,bizSkill:35,job:null,performance:55,workMode:'normal',businesses:[],holdings:{},properties:[],vehicles:[],spouse:null,dating:null,children:[],heir:null,marketCycle:'Normal',events:[['💡','You started planning your future.',18]],lastPassive:0,politics:{office:null,approval:50,reputation:10,campaignFunds:0,termLeft:0,terms:0,policies:0,scandals:0},military:{active:false,branch:null,rankIndex:0,officer:false,years:0,performance:55,deployments:0,medals:0,injuries:0,discharge:null,veteran:false,benefits:0}};
let previous=JSON.parse(localStorage.lifeGameP456||'null')||{};
let s={...defaults,...previous,...(JSON.parse(localStorage.lifeGameP9||'null')||{})};
['businesses','properties','vehicles','children'].forEach(k=>s[k]=s[k]||[]);s.holdings=s.holdings||{};s.politics={...defaults.politics,...(s.politics||{})};s.military={...defaults.military,...(s.military||{})};
const clamp=n=>Math.max(0,Math.min(100,Math.round(n))),money=n=>'$'+Math.round(n).toLocaleString(),save=()=>localStorage.lifeGameP9=JSON.stringify(s);
function add(i,t){s.events.push([i,t,s.age]);if(s.events.length>70)s.events.shift()}
function show(id,b){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));document.getElementById(id).classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');scrollTo(0,0);render()}
function tab(id,b){document.querySelectorAll('.pane').forEach(x=>x.classList.remove('on'));document.getElementById(id).classList.add('on');b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function businessValue(){return s.businesses.reduce((a,b)=>a+b.valuation,0)}function marketValue(){return marketDefs.reduce((a,m,i)=>a+(s.holdings[i]||0)*m[1],0)}function propertyEquity(){return s.properties.reduce((a,p)=>a+Math.max(0,p.value-p.mortgage),0)}function vehicleValue(){return s.vehicles.reduce((a,v)=>a+v.value,0)}function net(){return s.cash+s.savings+businessValue()+marketValue()+propertyEquity()+vehicleValue()}
function militaryRank(){let list=s.military.officer?officerRanks:enlistedRanks;return list[Math.min(s.military.rankIndex,list.length-1)]}
function role(){return s.military.active?militaryRank()+' • '+s.military.branch:s.politics.office?s.politics.office:s.businesses.some(b=>b.public)?'Public Company Founder':s.businesses.length?'Business Owner':s.job?s.job.title:s.military.veteran?'Veteran':'Investor'}
function fame(){let x=s.businesses.reduce((a,b)=>a+b.locations*8+b.franchises*10+(b.public?100:0),0)+s.politics.reputation*2+s.military.medals*8+s.military.rankIndex*3;return x>300?'Global':x>150?'National':x>70?'Statewide':x>25?'Regional':x>0?'Local':'Unknown'}
function render(){nameT.textContent=s.name;ageT.textContent='Age '+s.age;yearT.textContent=s.age;genT.textContent=s.generation;roleT.textContent=role();fameT.textContent=fame();netT.textContent=money(net());titleT.textContent=s.military.active?militaryRank():s.politics.office||(net()>=1e9?'Billionaire':net()>=1e6?'Millionaire':'Building Wealth');stats.innerHTML=[['❤️ Health',s.health,'#16b86a'],['😊 Happiness',s.happy,'#f6a21a'],['🧠 Smarts',s.smart,'#3e83f7'],['✦ Looks',s.looks,'#7c43ee'],['📊 Business',s.bizSkill,'#06a6a6']].map(x=>`<div class="stat"><b>${x[0]}</b><div class="track"><i style="width:${x[1]}%;background:${x[2]}"></i></div><span>${x[1]}%</span></div>`).join('');cashT.textContent=money(s.cash);events.innerHTML=s.events.slice(-4).reverse().map(e=>`<div class="event"><span style="font-size:20px">${e[0]}</span><span>${e[1]}</span><span class="small">Age ${e[2]}</span></div>`).join('');renderJobs();renderMilitary();renderBiz();renderEmpire();renderPortfolio();renderMarkets();renderProperty();renderRelationships();renderChildren();renderInheritance();renderVehicles();renderVehicleMarket();renderPolitics();renderCampaigns();renderPolicies();renderPoliticalLegacy();renderLegacy();save()}
function renderJobs(){jobs.innerHTML=(s.job?`<div class="item office"><h3>💼 ${s.job.title}</h3><div>${money(s.job.salary)}/yr • Performance ${s.performance}%</div><div class="actions"><button class="btn green" onclick="s.workMode='hard';render()">Work Hard</button><button class="btn blue" onclick="s.workMode='normal';render()">Normal</button><button class="btn red" onclick="s.workMode='slack';render()">Slack</button><button class="btn red" onclick="s.job=null;render()">Quit</button></div></div>`:'')+jobsData.map((j,i)=>`<div class="item"><div class="title"><div class="icon">💼</div><div><h3>${j[0]}</h3><div class="salary">${money(j[1])}/yr</div></div></div><div class="req">Age ${j[2]} • ${j[3]} smarts</div><button class="btn" ${s.job||s.military.active||s.age<j[2]||s.smart<j[3]?'disabled':''} onclick="applyJob(${i})">Apply</button></div>`).join('')}
function renderMilitary(){let m=s.military;if(m.active){let branch=militaryBranches.find(x=>x.name===m.branch),next=(m.officer?officerRanks:enlistedRanks)[m.rankIndex+1];military.innerHTML=`<div class="item office"><div class="small">ACTIVE DUTY</div><h3>${branch.icon} ${m.branch}</h3><div class="kpis"><div class="kpi">Rank<b>${militaryRank()}</b></div><div class="kpi">Service<b>${m.years} years</b></div><div class="kpi">Performance<b>${m.performance}%</b></div><div class="kpi">Deployments<b>${m.deployments}</b></div><div class="kpi">Medals<b>${m.medals}</b></div><div class="kpi">Injuries<b>${m.injuries}</b></div></div><div class="actions"><button class="btn green" onclick="militaryTraining()">Train Hard</button><button class="btn blue" onclick="volunteerDeployment()">Volunteer Deployment</button><button class="btn" ${!next?'disabled':''} onclick="requestPromotion()">Request Promotion</button><button class="btn red" onclick="leaveMilitary()">Request Discharge</button></div></div>`}else{military.innerHTML=(m.veteran?`<div class="item"><h3>🎖️ Veteran Benefits</h3><div class="small">Discharge: ${m.discharge||'Honorable'} • Medals ${m.medals} • Deployments ${m.deployments}</div><div class="salary">Annual benefits ${money(m.benefits||0)}</div><button class="btn blue" onclick="useVeteranPath()">Use Veteran Career Path</button></div>`:'')+militaryBranches.map((b,i)=>{let ok=!s.job&&!s.politics.office&&s.age>=b.minAge&&s.age<=b.maxAge&&s.health>=b.minHealth&&s.smart>=b.minSmart;return `<div class="item"><div class="title"><div class="icon">${b.icon}</div><div><h3>${b.name}</h3><div class="salary">${money(b.basePay)}/yr starting pay</div></div></div><div class="req">Age ${b.minAge}-${b.maxAge} • Health ${b.minHealth}+ • Smarts ${b.minSmart}+</div><div class="small">Deployment risk ${Math.round(b.risk*100)}% • Fitness +${b.fitness} • Skill +${b.skill}</div><div class="actions"><button class="btn" ${ok?'':'disabled'} onclick="enlist(${i},false)">Enlist</button><button class="btn blue" ${ok&&s.smart>=70?'':'disabled'} onclick="enlist(${i},true)">Officer Track</button></div></div>`}).join('')}}
function renderBiz(){biz.innerHTML=s.businesses.map((b,i)=>`<div class="item"><div class="row"><h3>🏢 ${b.name}</h3><span class="badge">${money(b.lastProfit||0)} profit</span></div><div class="kpis"><div class="kpi">Value<b>${money(b.valuation)}</b></div><div class="kpi">Locations<b>${b.locations}</b></div><div class="kpi">Employees<b>${b.employees}</b></div><div class="kpi">Franchises<b>${b.franchises}</b></div></div><div class="actions"><button class="btn green" onclick="upgradeBiz(${i})">Upgrade</button><button class="btn blue" onclick="hire(${i})">Hire</button><button class="btn" onclick="expandBiz(${i})">Expand</button></div></div>`).join('')+bizDefs.map((b,i)=>`<div class="item"><h3>🏢 ${b[0]}</h3><div class="small">Startup ${money(b[1])}</div><button class="btn" ${s.cash<b[1]?'disabled':''} onclick="startBiz(${i})">Launch</button></div>`).join('')}
function renderEmpire(){empire.innerHTML=s.businesses.map((b,i)=>`<div class="item"><h3>🏢 ${b.name}</h3><div class="small">${b.public?'Public':'Private'} • Market share ${b.marketShare.toFixed(1)}%</div><div class="actions"><button class="btn green" ${b.locations<3?'disabled':''} onclick="franchise(${i})">Franchise</button><button class="btn blue" onclick="buyRival(${i})">Buy Rival</button><button class="btn" ${b.valuation<1000000||b.public?'disabled':''} onclick="ipo(${i})">IPO</button></div></div>`).join('')||'<div class="item">Start a business first.</div>'}
function renderPortfolio(){portfolio.innerHTML=`<div class="grid2"><div class="card"><div class="small">Net Worth</div><div class="big">${money(net())}</div></div><div class="card"><div class="small">Passive Income</div><div class="big">${money(s.lastPassive||0)}</div></div></div><div class="item"><div class="small">Cash ${money(s.cash)} • Savings ${money(s.savings)} • Businesses ${money(businessValue())} • Markets ${money(marketValue())} • Property ${money(propertyEquity())} • Vehicles ${money(vehicleValue())}</div></div>`}
function renderMarkets(){markets.innerHTML=`<div class="item"><div class="row"><h3>Market Cycle</h3><span class="pill">${s.marketCycle}</span></div></div>`+marketDefs.map((m,i)=>`<div class="item"><div class="row"><h3>📈 ${m[0]}</h3><div><b>${money(m[1])}</b><div class="small">${(s.holdings[i]||0).toFixed(2)} shares</div></div></div><div class="actions"><button class="btn green" onclick="trade(${i},100)">Buy $100</button><button class="btn red" onclick="trade(${i},-1)">Sell 1</button></div></div>`).join('')}
function renderProperty(){property.innerHTML=s.properties.map((p,i)=>`<div class="item"><h3>🏠 ${p.name}</h3><div class="small">Value ${money(p.value)} • Mortgage ${money(p.mortgage)} • Rent ${money(p.lastRent||0)}</div><button class="btn red" onclick="sellProperty(${i})">Sell</button></div>`).join('')+propertyDefs.map((p,i)=>`<div class="item"><h3>🏠 ${p[0]}</h3><div class="small">Price ${money(p[1])} • Down ${money(p[2])}</div><button class="btn" ${s.cash<p[2]?'disabled':''} onclick="buyProperty(${i})">Buy</button></div>`).join('')}
function renderRelationships(){relationships.innerHTML=s.spouse?`<div class="item"><h3>💍 ${s.spouse.name}</h3><div class="small">Spouse • Relationship ${s.spouse.relationship}%</div><button class="btn green" onclick="dateNight()">Date Night</button></div>`:s.dating?`<div class="item"><h3>❤️ ${s.dating.name}</h3><div class="small">Dating • Relationship ${s.dating.relationship}%</div><div class="actions"><button class="btn green" onclick="dateNight()">Date</button><button class="btn" onclick="propose()">Propose</button></div></div>`:`<div class="item"><h3>Single</h3><button class="btn" onclick="findDate()">Find a Date</button></div>`}
function renderChildren(){children.innerHTML=(s.spouse?'<div class="item"><button class="btn green" onclick="haveChild()">Have a Child</button></div>':'')+s.children.map((c,i)=>`<div class="item"><h3>🧒 ${c.name}</h3><div class="small">Age ${c.age} • Smarts ${c.smart} • Relationship ${c.relationship}%</div><button class="btn" onclick="spendChild(${i})">Spend Time</button></div>`).join('')||'<div class="item">No children yet.</div>'}
function renderInheritance(){inheritance.innerHTML=`<div class="item"><h3>Chosen Heir</h3><div class="small">${s.heir!=null&&s.children[s.heir]?s.children[s.heir].name:'None'}</div></div>`+s.children.map((c,i)=>`<div class="item row"><span>${c.name}, age ${c.age}</span><button class="btn" onclick="s.heir=${i};render()">Choose</button></div>`).join('')}
function renderVehicles(){ownedVehicles.innerHTML=s.vehicles.map((v,i)=>`<div class="item"><div class="row"><h3>🚗 ${v.name}</h3><span class="badge">${money(v.value)}</span></div><div class="small">Condition ${v.condition}% • Annual cost ${money(v.cost)}</div><button class="btn red" onclick="sellVehicle(${i})">Sell</button></div>`).join('')||'<div class="item">Your garage is empty.</div>'}
function renderVehicleMarket(){vehicleMarket.innerHTML=vehicleDefs.map((v,i)=>`<div class="item"><h3>🚗 ${v[0]}</h3><div class="small">Price ${money(v[1])} • Annual cost ${money(v[3])}</div><button class="btn" ${s.cash<v[1]?'disabled':''} onclick="buyVehicle(${i})">Buy</button></div>`).join('')}
function renderPolitics(){let p=s.politics;politicsOverview.innerHTML=p.office?`<div class="item office"><div class="small">CURRENT OFFICE</div><h3>🏛️ ${p.office}</h3><div class="kpis"><div class="kpi">Approval<b>${p.approval}%</b></div><div class="kpi">Term Left<b>${p.termLeft} years</b></div><div class="kpi">Reputation<b>${p.reputation}</b></div><div class="kpi">Campaign Fund<b>${money(p.campaignFunds)}</b></div></div><div class="actions"><button class="btn green" onclick="fundraise()">Fundraise</button><button class="btn blue" onclick="townHall()">Town Hall</button><button class="btn red" onclick="resignOffice()">Resign</button></div></div>`:`<div class="item"><h3>No Political Office</h3><div class="small">Build reputation, raise money, and run for office.</div><button class="btn green" onclick="fundraise()">Start Fundraising</button></div>`}
function renderCampaigns(){campaigns.innerHTML=offices.map((o,i)=>{let ok=!s.politics.office&&!s.military.active&&s.age>=o.age&&s.politics.reputation>=o.need&&(s.cash+s.politics.campaignFunds)>=o.cost;return `<div class="item"><h3>🏛️ ${o.name}</h3><div class="small">Age ${o.age}+ • Campaign ${money(o.cost)} • Need ${o.need} reputation • ${o.term}-year term</div><button class="btn" ${ok?'':'disabled'} onclick="runElection(${i})">Run for Office</button></div>`}).join('')}
function renderPolicies(){policies.innerHTML=s.politics.office?policyDefs.map((p,i)=>`<div class="item"><h3>📜 ${p[0]}</h3><div class="small">Approval +${p[1]} • Business ${p[2]>=0?'+':''}${p[2]} • Reputation +${p[3]}</div><button class="btn" onclick="passPolicy(${i})">Sign Policy</button></div>`).join(''):'<div class="item">Win an election to govern.</div>'}
function renderPoliticalLegacy(){politicalLegacy.innerHTML=`<div class="grid2"><div class="card"><div class="small">Terms Served</div><div class="big">${s.politics.terms}</div></div><div class="card"><div class="small">Policies Passed</div><div class="big">${s.politics.policies}</div></div><div class="card"><div class="small">Reputation</div><div class="big">${s.politics.reputation}</div></div><div class="card"><div class="small">Scandals</div><div class="big">${s.politics.scandals}</div></div></div>`}
function renderLegacy(){let worth=net(),goals=[[1e6,'Millionaire'],[1e8,'Centi-Millionaire'],[1e9,'Billionaire']];legacyPane.innerHTML=`<div class="card"><h3>Generation ${s.generation} Dynasty</h3><div class="small">${s.children.length} children • ${s.businesses.filter(b=>b.public).length} public companies • ${s.politics.terms} political terms • ${s.military.years} years served • ${s.military.medals} medals</div></div>`+goals.map(g=>`<div class="card row"><div><b>${worth>=g[0]?'🏆':'🔒'} ${g[1]}</b><div class="small">Reach ${money(g[0])}</div></div><span class="pill">${Math.min(100,Math.round(worth/g[0]*100))}%</span></div>`).join('')}