const educationDefs=[
{icon:'🎓',name:'Community College',years:2,cost:12000,age:18,smart:35,type:'degree',reward:8},
{icon:'🏛️',name:'University',years:4,cost:42000,age:18,smart:50,type:'degree',reward:15},
{icon:'💼',name:'MBA',years:2,cost:48000,age:22,smart:70,type:'degree',reward:10,requires:'University'},
{icon:'⚖️',name:'Law School',years:3,cost:90000,age:22,smart:82,type:'degree',reward:12,requires:'University'},
{icon:'🩺',name:'Medical School',years:4,cost:140000,age:22,smart:90,type:'degree',reward:14,requires:'University'},
{icon:'🚛',name:'CDL School',years:1,cost:5500,age:18,smart:20,type:'license',license:'Class A CDL',reward:4},
{icon:'🏠',name:'Real Estate Course',years:1,cost:1200,age:18,smart:35,type:'license',license:'Real Estate License',reward:3},
{icon:'🔥',name:'Welding Certification',years:1,cost:6500,age:18,smart:25,type:'license',license:'Welding Certification',reward:4},
{icon:'✈️',name:'Pilot Training',years:2,cost:65000,age:18,smart:65,type:'license',license:'Commercial Pilot License',reward:7},
{icon:'🛡️',name:'Police Academy',years:1,cost:4000,age:21,smart:45,type:'license',license:'Peace Officer License',reward:5}
];
const sportsDefs=[
{icon:'🏈',name:'Football',ageMax:25,health:75,skill:'athleticism',rookie:650000,risk:.22},
{icon:'🏀',name:'Basketball',ageMax:24,health:72,skill:'athleticism',rookie:900000,risk:.16},
{icon:'🥊',name:'Boxing',ageMax:34,health:70,skill:'combatSkill',rookie:120000,risk:.28},
{icon:'🥋',name:'MMA',ageMax:33,health:75,skill:'combatSkill',rookie:150000,risk:.3},
{icon:'🏎️',name:'Racing',ageMax:35,health:60,skill:'racingSkill',rookie:300000,risk:.2},
{icon:'🏋️',name:'Bodybuilding',ageMax:40,health:80,skill:'athleticism',rookie:80000,risk:.1}
];
const choiceEvents=[
{icon:'💼',title:'Competitor Buyout',text:'A competitor offers to buy one of your businesses for 1.4× its value.',when:()=>s.businesses.length>0,choices:[['Accept Offer',()=>{let b=s.businesses.shift(),v=Math.round(b.valuation*1.4);s.cash+=v;add('🤝','You sold '+b.name+' for '+money(v)+'.')}],['Reject It',()=>{s.bizSkill=clamp(s.bizSkill+3);add('💪','You rejected the buyout and stayed independent.')}]]},
{icon:'🔥',title:'House Fire',text:'A fire damages one of your properties. How do you respond?',when:()=>s.properties.length>0,choices:[['Pay for Repairs',()=>{let p=s.properties[0],c=Math.round(p.value*.06);s.cash-=c;p.value=Math.round(p.value*.98);add('🔧','You paid '+money(c)+' for fire repairs.')}],['Sell As-Is',()=>{let p=s.properties.shift();s.cash+=Math.round((p.value-p.mortgage)*.65);add('🏚️','You sold the damaged property as-is.')}]]},
{icon:'💰',title:'Found Wallet',text:'You find a wallet containing $2,000 and identification.',choices:[['Return It',()=>{s.happy=clamp(s.happy+8);s.politics.reputation=clamp(s.politics.reputation+5);add('😇','You returned the wallet to its owner.')}],['Keep the Cash',()=>{s.cash+=2000;s.politics.reputation=clamp(s.politics.reputation-4);add('💵','You kept the money from the wallet.')}]]},
{icon:'📰',title:'Interview Request',text:'A major news outlet asks to interview you about your success.',when:()=>net()>500000||s.politics.office||s.sports.active,choices:[['Accept',()=>{s.looks=clamp(s.looks+2);s.politics.reputation=clamp(s.politics.reputation+6);add('🎙️','Your interview raised your public profile.')}],['Decline',()=>{s.happy=clamp(s.happy+2);add('🤫','You chose to remain private.')}]]},
{icon:'⚖️',title:'Business Lawsuit',text:'A customer threatens to sue your company.',when:()=>s.businesses.length>0,choices:[['Settle for $25,000',()=>{s.cash-=25000;add('⚖️','You settled the lawsuit.')}],['Fight in Court',()=>{if(Math.random()<.55){add('🏆','You won the lawsuit.')}else{s.cash-=90000;add('💸','You lost the lawsuit and paid damages.')}}]]},
{icon:'❤️',title:'Friend in Need',text:'A close friend asks to borrow $5,000.',choices:[['Help Them',()=>{s.cash-=5000;s.happy=clamp(s.happy+6);add('🤝','You helped a friend through a difficult time.')}],['Say No',()=>{s.happy=clamp(s.happy-2);add('🚫','You declined to lend the money.')}]]},
{icon:'🎖️',title:'Dangerous Assignment',text:'Your commander offers you a dangerous mission with promotion potential.',when:()=>s.military&&s.military.active,choices:[['Accept Mission',()=>{if(Math.random()<.65){s.military.performance=clamp(s.military.performance+18);s.military.medals++;add('🎖️','You completed the dangerous assignment.')}else{s.health=clamp(s.health-22);s.military.injuries++;add('🩹','You were injured on the assignment.')}}],['Decline',()=>{s.military.performance=clamp(s.military.performance-5);add('📋','You declined the dangerous assignment.')}]]},
{icon:'🏆',title:'Sponsorship Offer',text:'A brand offers you a sponsorship worth $75,000.',when:()=>s.sports&&s.sports.active&&s.sports.fame>=25,choices:[['Sign Deal',()=>{s.cash+=75000;s.sports.fame+=5;add('📣','You signed a major sponsorship deal.')}],['Hold Out',()=>{if(Math.random()<.35){s.cash+=180000;s.sports.fame+=8;add('💎','Holding out earned you a bigger deal.')}else add('❌','The sponsor withdrew its offer.')}]]}
];
s.education=s.education||{completed:['High School'],licenses:[],enrollment:null,studentDebt:0};
s.education.completed=s.education.completed||['High School'];s.education.licenses=s.education.licenses||[];
s.sports=s.sports||{active:false,sport:null,skill:20,athleticism:35,combatSkill:20,racingSkill:20,seasonPerformance:50,contract:0,contractYears:0,careerYears:0,championships:0,awards:0,fame:0,injuries:0,retired:false,earnings:0};
const originalRole=role;role=function(){if(s.sports.active)return 'Professional '+s.sports.sport+' Athlete';if(s.education.enrollment)return s.education.enrollment.name+' Student';return originalRole()};
const originalRender=render;render=function(){originalRender();renderEducation();renderSports()};
function renderEducation(){let e=s.education;education.innerHTML=(e.enrollment?`<div class="item office"><div class="small">CURRENT PROGRAM</div><h3>${e.enrollment.icon} ${e.enrollment.name}</h3><div class="kpis"><div class="kpi">Years Left<b>${e.enrollment.yearsLeft}</b></div><div class="kpi">Tuition Paid<b>${money(e.enrollment.cost)}</b></div></div><button class="btn red" onclick="dropEducation()">Drop Out</button></div>`:'')+`<div class="item"><h3>Qualifications</h3><div class="small">Education: ${e.completed.join(', ')||'None'}</div><div class="small">Licenses: ${e.licenses.join(', ')||'None'}</div><div class="small">Student debt: ${money(e.studentDebt)}</div></div>`+educationDefs.map((d,i)=>{let done=e.completed.includes(d.name)||(d.license&&e.licenses.includes(d.license)),req=!d.requires||e.completed.includes(d.requires),ok=!e.enrollment&&!done&&req&&s.age>=d.age&&s.smart>=d.smart;return `<div class="item"><div class="title"><div class="icon">${d.icon}</div><div><h3>${d.name}</h3><div class="small">${d.years} year(s) • ${money(d.cost)} • Smarts ${d.smart}+</div></div></div>${d.requires?`<div class="req">Requires ${d.requires}</div>`:''}<div class="actions"><button class="btn" ${ok?'':'disabled'} onclick="enrollEducation(${i},false)">Pay Tuition</button><button class="btn blue" ${ok?'':'disabled'} onclick="enrollEducation(${i},true)">Use Student Loan</button></div></div>`}).join('')+`<div class="item"><h3>Licensed Career Shortcuts</h3><div class="actions"><button class="btn" ${e.licenses.includes('Class A CDL')&&!s.job?'':'disabled'} onclick="licensedJob('CDL Driver',78000)">CDL Driver</button><button class="btn" ${e.licenses.includes('Real Estate License')&&!s.job?'':'disabled'} onclick="licensedJob('Licensed Real Estate Agent',92000)">Real Estate Agent</button><button class="btn" ${e.licenses.includes('Welding Certification')&&!s.job?'':'disabled'} onclick="licensedJob('Certified Welder',68000)">Welder</button><button class="btn" ${e.licenses.includes('Commercial Pilot License')&&!s.job?'':'disabled'} onclick="licensedJob('Commercial Pilot',135000)">Pilot</button></div></div>`}
function renderSports(){let a=s.sports;if(a.active){sports.innerHTML=`<div class="item office"><div class="small">PRO ATHLETE</div><h3>🏆 ${a.sport}</h3><div class="kpis"><div class="kpi">Skill<b>${a.skill}%</b></div><div class="kpi">Season<b>${a.seasonPerformance}%</b></div><div class="kpi">Contract<b>${money(a.contract)}/yr</b></div><div class="kpi">Years Left<b>${a.contractYears}</b></div><div class="kpi">Fame<b>${a.fame}</b></div><div class="kpi">Titles<b>${a.championships}</b></div></div><div class="actions"><button class="btn green" onclick="trainSport()">Train</button><button class="btn blue" onclick="playExtraEvent()">Extra Event</button><button class="btn" onclick="negotiateContract()">Negotiate</button><button class="btn red" onclick="retireSport()">Retire</button></div></div>`}else{sports.innerHTML=(a.retired?`<div class="item"><h3>🏅 Retired Athlete</h3><div class="small">Career earnings ${money(a.earnings)} • Championships ${a.championships} • Awards ${a.awards}</div><button class="btn blue" onclick="sportsBroadcastJob()">Become Sports Analyst</button></div>`:'')+sportsDefs.map((d,i)=>{let stat=s.sports[d.skill]||0,ok=!s.job&&!s.military.active&&!s.politics.office&&!a.retired&&s.age<=d.ageMax&&s.health>=d.health&&stat>=30;return `<div class="item"><div class="title"><div class="icon">${d.icon}</div><div><h3>${d.name}</h3><div class="salary">Rookie pay ${money(d.rookie)}/yr</div></div></div><div class="req">Max entry age ${d.ageMax} • Health ${d.health}+ • Skill 30+</div><div class="actions"><button class="btn green" onclick="practiceSport('${d.skill}')">Practice</button><button class="btn" ${ok?'':'disabled'} onclick="tryoutSport(${i})">Attend Tryout</button></div></div>`}).join('')}}
function enrollEducation(i,loan){let d=educationDefs[i];if(s.education.enrollment)return toast('Finish your current program first');if(!loan&&s.cash<d.cost)return toast('Not enough cash');if(loan)s.education.studentDebt+=Math.round(d.cost*1.15);else s.cash-=d.cost;s.education.enrollment={...d,yearsLeft:d.years};add('📚','You enrolled in '+d.name+'.');render()}
function dropEducation(){let n=s.education.enrollment.name;s.education.enrollment=null;add('📕','You dropped out of '+n+'.');render()}
function licensedJob(title,salary){if(s.job||s.military.active||s.sports.active)return toast('Leave your current career first');s.job={title,salary};s.performance=60;add('💼','Your license helped you become a '+title+'.');render()}
function practiceSport(stat){s.sports[stat]=clamp((s.sports[stat]||0)+8);s.health=clamp(s.health+4);s.happy=clamp(s.happy+2);add('🏋️','You practiced and improved your athletic ability.');render()}
function tryoutSport(i){let d=sportsDefs[i],stat=s.sports[d.skill]||0,chance=.25+stat/130+s.health/350;if(Math.random()<chance){s.sports={...s.sports,active:true,sport:d.name,skill:stat,seasonPerformance:55,contract:d.rookie,contractYears:3,careerYears:0,fame:5,retired:false};s.job=null;add('🏆','You signed a professional '+d.name+' contract!')}else add('📋','You were cut after the '+d.name+' tryout.');render()}
function trainSport(){s.sports.skill=clamp(s.sports.skill+7);s.sports.seasonPerformance=clamp(s.sports.seasonPerformance+5);s.health=clamp(s.health+3);render()}
function playExtraEvent(){let d=sportsDefs.find(x=>x.name===s.sports.sport),r=Math.random();if(r<d.risk*.45){s.sports.injuries++;s.health=clamp(s.health-18);s.sports.seasonPerformance=clamp(s.sports.seasonPerformance-12);add('🩹','You were injured during competition.')}else{s.sports.seasonPerformance=clamp(s.sports.seasonPerformance+10);s.sports.fame+=4;add('🌟','You delivered a standout performance.')}render()}
function negotiateContract(){if(s.sports.contractYears>1)return toast('Your contract is not close to expiring');let offer=Math.round(s.sports.contract*(1.1+s.sports.seasonPerformance/100+s.sports.fame/200));if(Math.random()<.72){s.sports.contract=offer;s.sports.contractYears=3;add('✍️','You signed a new '+money(offer)+' annual contract.')}else add('❌','Contract negotiations failed.');render()}
function retireSport(){s.sports.active=false;s.sports.retired=true;add('🏅','You retired from professional '+s.sports.sport+'.');render()}
function sportsBroadcastJob(){if(s.job)return;s.job={title:'Sports Analyst',salary:95000+s.sports.fame*1500};s.performance=65;render()}
const baseRunYear=runYear;runYear=function(){baseRunYear();runEducationYear();runSportsYear()};
function runEducationYear(){let e=s.education;if(e.studentDebt>0){let payment=Math.min(e.studentDebt,Math.max(1200,Math.round(e.studentDebt*.08)));e.studentDebt-=payment;s.cash-=payment}if(!e.enrollment)return;e.enrollment.yearsLeft--;s.smart=clamp(s.smart+3);if(e.enrollment.yearsLeft<=0){let d=e.enrollment;if(d.license)e.licenses.push(d.license);else e.completed.push(d.name);s.smart=clamp(s.smart+d.reward);add('🎓','You completed '+d.name+(d.license?' and earned your '+d.license:'')+'.');e.enrollment=null}}
function runSportsYear(){let a=s.sports;if(!a.active)return;let d=sportsDefs.find(x=>x.name===a.sport);a.careerYears++;a.contractYears--;a.earnings+=a.contract;s.cash+=a.contract;a.seasonPerformance=clamp(a.seasonPerformance+(Math.random()*18-7)+a.skill/20);a.fame+=Math.max(0,Math.round((a.seasonPerformance-45)/12));if(Math.random()<d.risk){a.injuries++;s.health=clamp(s.health-(8+Math.random()*18));a.seasonPerformance=clamp(a.seasonPerformance-15);add('🩹','A sports injury affected your season.')}if(a.seasonPerformance>88&&Math.random()<.45){a.championships++;a.fame+=15;a.awards++;add('🏆','You won a championship!')}else if(a.seasonPerformance>78&&Math.random()<.35){a.awards++;a.fame+=7;add('🥇','You earned a major individual award.')}if(a.contractYears<=0){a.contract=Math.round(a.contract*(.85+a.seasonPerformance/75+a.fame/180));a.contractYears=3;add('✍️','You signed a new contract worth '+money(a.contract)+' per year.')}let retirementAge=d.name==='Bodybuilding'?48:d.name==='Boxing'||d.name==='MMA'?42:40;if(s.age>=retirementAge||s.health<30){a.active=false;a.retired=true;add('🏅','You retired from '+a.sport+' after '+a.careerYears+' seasons.')}}
const baseAgeUp=ageUp;ageUp=function(){baseAgeUp();maybeChoiceEvent()};
function maybeChoiceEvent(){if(Math.random()>.55)return;let possible=choiceEvents.filter(e=>!e.when||e.when());if(!possible.length)return;let e=possible[Math.floor(Math.random()*possible.length)];showChoiceEvent(e)}
function showChoiceEvent(e){choiceIcon.textContent=e.icon;choiceTitle.textContent=e.title;choiceText.textContent=e.text;choiceButtons.innerHTML='';e.choices.forEach(c=>{let b=document.createElement('button');b.className='choice-option';b.textContent=c[0];b.onclick=()=>{choiceModal.classList.remove('on');c[1]();render()};choiceButtons.appendChild(b)});choiceModal.classList.add('on')}
render();